when:
  - event: push
    branch: main

steps:
  - name: build
    image: node:25
    commands:
      - npm install --global bun@1.3.2
      - make setup
      - make build
  - name: test
    image: node:25
    commands:
      - npm install --global bun@1.3.2
      - make setup
      - make lint
      - make test
